mappings:
  MockChildrenController: UncleCheese\MockDataObjects\Admin\MockChildrenController
  MockDataCMS: UncleCheese\MockDataObjects\Extensions\MockDataCMS
  MockDataGridFieldItemRequest: UncleCheese\MockDataObjects\Extensions\MockDataGridFieldItemRequest
  MockDataObject: UncleCheese\MockDataObjects\Extensions\MockDataObject
  MockDataObjectGridFieldConfig: UncleCheese\MockDataObjects\Extensions\MockDataObjectGridFieldConfig
  MockDataSiteTree: UncleCheese\MockDataObjects\Extensions\MockDataSiteTree
  MockViewableData: UncleCheese\MockDataObjects\Extensions\MockViewableData
  MockBooleanField: UncleCheese\MockDataObjects\FieldTypes\MockBooleanField
  MockCurrencyField: UncleCheese\MockDataObjects\FieldTypes\MockCurrencyField
  MockDateField: UncleCheese\MockDataObjects\FieldTypes\MockDateField
  MockDatetimeField: UncleCheese\MockDataObjects\FieldTypes\MockDatetimeField
  MockDBField: UncleCheese\MockDataObjects\FieldTypes\MockDBField
  MockDecimalField: UncleCheese\MockDataObjects\FieldTypes\MockDecimalField
  MockDoubleField: UncleCheese\MockDataObjects\FieldTypes\MockDoubleField
  MockFloatField: UncleCheese\MockDataObjects\FieldTypes\MockFloatField
  MockHTMLTextField: UncleCheese\MockDataObjects\FieldTypes\MockHTMLTextField
  MockHTMLVarcharField: UncleCheese\MockDataObjects\FieldTypes\MockHTMLVarcharField
  MockIntField: UncleCheese\MockDataObjects\FieldTypes\MockIntField
  MockPercentageField: UncleCheese\MockDataObjects\FieldTypes\MockPercentageField
  MockTextField: UncleCheese\MockDataObjects\FieldTypes\MockTextField
  MockTimeField: UncleCheese\MockDataObjects\FieldTypes\MockTimeField
  MockVarcharField: UncleCheese\MockDataObjects\FieldTypes\MockVarcharField
  MockYearField: UncleCheese\MockDataObjects\FieldTypes\MockYearField
  MockDataGenerator: UncleCheese\MockDataObjects\GridField\MockDataGenerator
  MockDataLog: UncleCheese\MockDataObjects\Models\MockDataLog
  MockDataBuilder: UncleCheese\MockDataObjects\Tasks\MockDataBuilder
  MockDataTask: UncleCheese\MockDataObjects\Tasks\MockDataTask
  MockDataObjectTest: UncleCheese\MockDataObjects\Test\MockDataObjectTest
  MockDataObjectTest_Person: UncleCheese\MockDataObjects\Test\Person
  MockDataObjectTest_Certification: UncleCheese\MockDataObjects\Test\Certification
  MockDataObjectTest_ServiceArea: UncleCheese\MockDataObjects\Test\ServiceArea